[tools]
java = "openjdk-21"
node = "latest"

[env]
ANDROID_HOME = "/home/armaldio/Android/Sdk"

[tasks.build]
run = "pnpm build"

[tasks.sync]    
run = "pnpm cap sync"
depends = ["build"]

[tasks.build-android]
run = "pnpm cap build android"
depends = ["sync"]

[tasks.run-android-dev]
run = "pnpm cap run android"
env = { NODE_ENV = "development" }

[tasks.run-android-prod]
run = "pnpm cap run android"
env = { NODE_ENV = "production" }
depends = ["sync"]
